import Category from "./Category";
import Users from "./Users";
import Posts from "./Posts";
import Comments from "./Comments";
import NotFound from "./NotFound";
import Home from "./Home";
import UserUpdate from "./Users/UserUpdate";
import CategoryUpdate from "./Category/CategoryUpdate";
import PostUpdate from "./Posts/PostUpdate";
import CreatePost from "./Posts/CreatePost";
import PostDetails from "./Posts/PostDetails";
export {Category, Users, Posts, Comments, NotFound , Home , UserUpdate  , CategoryUpdate , PostUpdate , CreatePost , PostDetails};